// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf5IEh2JH8VnD_3tfJKqTbDDRl2uA3EYw',
    appId: '1:809415721892:web:e7b425b8b714c828fcf731',
    messagingSenderId: '809415721892',
    projectId: 'cine-stream-12d47',
    authDomain: 'cine-stream-12d47.firebaseapp.com',
    storageBucket: 'cine-stream-12d47.firebasestorage.app',
    measurementId: 'G-HVQF1S4T64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-mxRawAGjt931O0LGsCeBvqMbJy8TAM',
    appId: '1:809415721892:android:07a0470b7d816e2cfcf731',
    messagingSenderId: '809415721892',
    projectId: 'cine-stream-12d47',
    storageBucket: 'cine-stream-12d47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL9AmRzJVoeohvrjCwCkr4AjnqOyfrrWs',
    appId: '1:809415721892:ios:ec22f9711081c3ecfcf731',
    messagingSenderId: '809415721892',
    projectId: 'cine-stream-12d47',
    storageBucket: 'cine-stream-12d47.firebasestorage.app',
    iosBundleId: 'com.example.cineStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL9AmRzJVoeohvrjCwCkr4AjnqOyfrrWs',
    appId: '1:809415721892:ios:ec22f9711081c3ecfcf731',
    messagingSenderId: '809415721892',
    projectId: 'cine-stream-12d47',
    storageBucket: 'cine-stream-12d47.firebasestorage.app',
    iosBundleId: 'com.example.cineStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf5IEh2JH8VnD_3tfJKqTbDDRl2uA3EYw',
    appId: '1:809415721892:web:a427e08685089036fcf731',
    messagingSenderId: '809415721892',
    projectId: 'cine-stream-12d47',
    authDomain: 'cine-stream-12d47.firebaseapp.com',
    storageBucket: 'cine-stream-12d47.firebasestorage.app',
    measurementId: 'G-K3FGE8E62C',
  );
}
